language: node_js
node_js:
  - "0.12"
sudo: false
notifications:
  email:
    recipients:
      - kim@web-flight.nl
    on_success: change
    on_failure: always
before_install: "npm link"
script: "npm run build"